### ISSUE TITLE
[PE-D][Tester D] UI bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-4/tp#141]
![image.png](https://raw.githubusercontent.com/ph-nathan/ped/main/files/c86abef5-3f5a-4f6e-9b60-d895ec5db841.png)
- How to replicate: Use “add” command to add in a duplicate member
- Possible bug: UI-related: The error message says “address book” instead of “TuitionConnect system" for instance. 

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: ph-nathan/ped#1

**Comment by WinstonLeonard** [comment]
resolved
