### ISSUE TITLE
[PE-D][Tester B] Command examples for "edit" in UG gives "Invalid command format" error in the app

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-4/tp#152]
The command examples in UG does not work in the app

`edit p/91234567 d/Sun`

`edit n/Betsy Crower a/Betsy street, block 110, #03-02`

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: larrywang0701/ped#3

**Comment by yihfei** [comment]
- added indexes to make these edit commands valid
