### ISSUE TITLE
[PE-D][Tester B] Several command accepts redundant content after the command itself

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-4/tp#154]
Some command does not check whether that are redundant input contents. For example, the following commands can execute without any errors:

`help abcdefg`

`unpaidAll abcdefg`

`undo abcdefg`

`redo abcdefg`

`rev abcdefg`

`exit abcdefg`

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: larrywang0701/ped#4

**Comment by lambraydon** [comment]
Not a bug
